### PR TITLE
update sb_replace_files

### PR DESCRIPTION
**Pull request by amsnyder**
Switching sb_replace_files with sb_replace_files_log function. This seems to fix the upload of unwanted files.

### CODE REVIEW

**Comment by amsnyder** [comment]
@SimonTopp - could you manually delete the extra files from SB and test this out to make sure they are not uploaded with this fix?

**Review by SimonTopp — APPROVED** [review]
Edit: See below comment.

**Comment by SimonTopp** [comment]
@amsnyder, I actually just double checked this.  I deleted one of the _wanted files_ and ran `scmake()` again just to make sure it would catch the change and push it to SB and it doesn't.  Is this expected behavior?

**Comment by amsnyder** [comment]
I think the pipeline only catches changes if you update a file locally...so perhaps deleting the file on SB won't trigger it to re-upload. It might be nice to fix this in the future - but our hope is that you have to do almost nothing manually in the SB edit page GUI.

You could manually add that file back for now, or make a small change (like whitespace) so that the timestamp on the file updates, and I think that will trigger the pipeline to reupload.

**Comment by SimonTopp** [comment]
Gotcha.  Not suggesting changes here, but just so you know.  Changing the inputs to the upstream targets (files to be zipped), didn't trigger a rebuild of those targets. However, just deleting the output of the upstream targets (the zipped file), did trigger a rebuild and sent it up to SB.  Nothing got pushed to SB when just changing the original inputs because the previous output (zipped file) hadn't changed.  Does that make sense?

**Comment by amsnyder** [comment]
Yes that makes sense. I'll open an issue so we track this and maybe update it in the future. For now, we will just have to remember that this is a limitation of the functionality.

**Comment by SimonTopp** [comment]
Love it, I'm going to go ahead and merge this.

**Pull request merged**
